# Path to your oh-my-zsh installation.
export ZSH=/home/$USER/.oh-my-zsh

ZSH_THEME="alpap"


plugins=(git colorise npm zsh-autosuggestions zsh-navigation-tools zsh-syntax-highlighting command-not-found cp docker dotenv)

source $ZSH/oh-my-zsh.sh
ENABLE_CORRECTION="true"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8


# Preferred editor for local and remote sesions

